"""empty message

Revision ID: 16a88d6b8226
Revises: 83b74066dd5a
Create Date: 2024-04-01 14:55:12.625342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16a88d6b8226'
down_revision = '83b74066dd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.alter_column('tagline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('tagline',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
