"""empty message

Revision ID: 26969cbd16ce
Revises: 336bfb47fb9f
Create Date: 2024-03-22 11:29:21.645564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26969cbd16ce'
down_revision = '336bfb47fb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specializationin', sa.String(length=50), nullable=True))
        batch_op.drop_column('specializationdin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specializationdin', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('specializationin')

    # ### end Alembic commands ###
