"""empty message

Revision ID: 336bfb47fb9f
Revises: d1d36d588172
Create Date: 2024-03-22 10:58:33.501545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336bfb47fb9f'
down_revision = 'd1d36d588172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intrestedin_course', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('tenth_board', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tenthpass_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenth_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tenth_schoolname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('twelfth_board', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('twelfthpass_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('twelfth_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('twelfth_schoolname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('specializationdin', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('specializationdin')
        batch_op.drop_column('twelfth_schoolname')
        batch_op.drop_column('twelfth_percentage')
        batch_op.drop_column('twelfthpass_year')
        batch_op.drop_column('twelfth_board')
        batch_op.drop_column('tenth_schoolname')
        batch_op.drop_column('tenth_percentage')
        batch_op.drop_column('tenthpass_year')
        batch_op.drop_column('tenth_board')
        batch_op.drop_column('link')
        batch_op.drop_column('gender')
        batch_op.drop_column('intrestedin_course')
        batch_op.drop_column('mobile_no')

    # ### end Alembic commands ###
