"""empty message

Revision ID: 359a6e99e2e6
Revises: 
Create Date: 2024-03-19 13:26:28.709873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359a6e99e2e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_table',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('jti', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('university_table',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('aicte', sa.String(length=50), nullable=True),
    sa.Column('ugc', sa.String(length=50), nullable=True),
    sa.Column('mhrd', sa.String(length=50), nullable=True),
    sa.Column('estd', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('university_id')
    )
    op.create_table('user_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('college_table',
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('estd', sa.Integer(), nullable=False),
    sa.Column('aicte', sa.String(length=50), nullable=True),
    sa.Column('mhrd', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university_table.university_id'], ),
    sa.PrimaryKeyConstraint('college_id')
    )
    op.create_table('admission_table',
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('eligibility', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cutoff', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.PrimaryKeyConstraint('admission_id')
    )
    op.create_table('course_table',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.String(length=255), nullable=True),
    sa.Column('application_begain', sa.Date(), nullable=True),
    sa.Column('application_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university_table.university_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('cutoff_table',
    sa.Column('cutoff_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('Quota', sa.String(length=100), nullable=True),
    sa.Column('open', sa.Integer(), nullable=True),
    sa.Column('close', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.PrimaryKeyConstraint('cutoff_id')
    )
    op.create_table('faculty_table',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university_table.university_id'], ),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_table('gallery_table',
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university_table.university_id'], ),
    sa.PrimaryKeyConstraint('gallery_id')
    )
    op.create_table('hostel_table',
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.PrimaryKeyConstraint('hostel_id')
    )
    op.create_table('info_table',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=255), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_table.admin_id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('news_table',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('news', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('question_table',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('rank_table',
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('by', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university_table.university_id'], ),
    sa.PrimaryKeyConstraint('rank_id')
    )
    op.create_table('review_table',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('like', sa.String(length=255), nullable=True),
    sa.Column('dislike', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('course_curriculum_overview', sa.String(length=255), nullable=False),
    sa.Column('placement_experience', sa.String(length=255), nullable=False),
    sa.Column('loan_scholarship_provisions', sa.String(length=255), nullable=False),
    sa.Column('campus_life', sa.String(length=255), nullable=False),
    sa.Column('admission', sa.String(length=255), nullable=False),
    sa.Column('classroom_size', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('current', sa.DateTime(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('college', sa.Integer(), nullable=True),
    sa.Column('internship', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('hostel', sa.Integer(), nullable=True),
    sa.Column('campus', sa.Integer(), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('answer_table',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('current', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_table.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('fee_table',
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('min_fee', sa.Integer(), nullable=False),
    sa.Column('max_fee', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course_table.course_id'], ),
    sa.PrimaryKeyConstraint('fee_id')
    )
    op.create_table('placement_table',
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('student_no', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_table.college_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course_table.course_id'], ),
    sa.PrimaryKeyConstraint('placement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_table')
    op.drop_table('fee_table')
    op.drop_table('answer_table')
    op.drop_table('review_table')
    op.drop_table('rank_table')
    op.drop_table('question_table')
    op.drop_table('news_table')
    op.drop_table('info_table')
    op.drop_table('hostel_table')
    op.drop_table('gallery_table')
    op.drop_table('faculty_table')
    op.drop_table('cutoff_table')
    op.drop_table('course_table')
    op.drop_table('admission_table')
    op.drop_table('college_table')
    op.drop_table('user_table')
    op.drop_table('university_table')
    op.drop_table('admin_table')
    # ### end Alembic commands ###
