"""empty message

Revision ID: 3d38071db195
Revises: 45e5117803af
Create Date: 2024-03-27 11:01:05.269332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d38071db195'
down_revision = '45e5117803af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.drop_column('remark')
        batch_op.drop_column('current')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
