"""empty message

Revision ID: 3dd03f5325d7
Revises: bfc49f9b18ac
Create Date: 2024-03-28 10:17:55.459514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd03f5325d7'
down_revision = 'bfc49f9b18ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'university_table', ['university_id'], ['university_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
