"""empty message

Revision ID: 45e5117803af
Revises: 99c876c78c86
Create Date: 2024-03-26 14:51:14.195908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45e5117803af'
down_revision = '99c876c78c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('college_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'college_table', ['college_id'], ['college_id'])
        batch_op.drop_column('current')

    with op.batch_alter_table('question_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_table', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('college_id')
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
