"""empty message

Revision ID: 4710c0d8a8c6
Revises: 3d38071db195
Create Date: 2024-03-27 11:10:14.494453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4710c0d8a8c6'
down_revision = '3d38071db195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_facilities', sa.String(length=255), nullable=False))
        batch_op.alter_column('like',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.alter_column('like',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('hostel_facilities')

    # ### end Alembic commands ###
