"""empty message

Revision ID: 83b74066dd5a
Revises: 6a7e926ed75e
Create Date: 2024-03-29 16:03:27.263764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83b74066dd5a'
down_revision = '6a7e926ed75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=False))
        batch_op.drop_column('news')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('tagline')

    # ### end Alembic commands ###
