"""empty message

Revision ID: 876af3408ab3
Revises: 3dd03f5325d7
Create Date: 2024-03-28 10:18:57.239291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876af3408ab3'
down_revision = '3dd03f5325d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'university_table', ['university_id'], ['university_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
