"""empty message

Revision ID: 940bd32a3609
Revises: 4710c0d8a8c6
Create Date: 2024-03-27 11:38:05.131959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940bd32a3609'
down_revision = '4710c0d8a8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internship_opportunitie', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.drop_column('internship_opportunitie')

    # ### end Alembic commands ###
