"""empty message

Revision ID: 9d52d4270585
Revises: 16a88d6b8226
Create Date: 2024-04-12 14:37:31.228922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d52d4270585'
down_revision = '16a88d6b8226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=255), nullable=True))
        batch_op.drop_column('article')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
