"""empty message

Revision ID: ab0ca9e89c05
Revises: 940bd32a3609
Create Date: 2024-03-27 11:39:47.587437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab0ca9e89c05'
down_revision = '940bd32a3609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internship_opportunities', sa.String(length=255), nullable=False))
        batch_op.drop_column('internship_opportunitie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internship_opportunitie', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('internship_opportunities')

    # ### end Alembic commands ###
