"""empty message

Revision ID: d8130478a3f9
Revises: 876af3408ab3
Create Date: 2024-03-28 10:21:07.177520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8130478a3f9'
down_revision = '876af3408ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'university_table', ['university_id'], ['university_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###
