"""empty message

Revision ID: eafc59adcea0
Revises: 26969cbd16ce
Create Date: 2024-03-22 12:47:57.783386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafc59adcea0'
down_revision = '26969cbd16ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
